sudo: false
language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - develop
before_install: 
  - git clone https://github.com/jcryptool/crypto.git ~/build/jcryptool/crypto
  - git checkout develop
  - echo "MAVEN_OPTS=-Xmx2048m" > ~/.mavenrc
install: true
script:
  - mvn -f org.jcryptool.releng/pom.xml -DskipTests=true