language: java
jdk:
- openjdk11
branches:
  only:
  - develop
before_install:
- git clone https://github.com/jcryptool/crypto.git ~/build/jcryptool/crypto
- echo "MAVEN_OPTS=-Xmx2048m" > ~/.mavenrc
install: true
script:
- mvn clean verify -f org.jcryptool.releng/pom.xml -DskipTests=true
before_deploy:
- git config --local user.name "Dominik Schadow"
- git config --local user.email "dominikschadow@gmail.com"
- git tag "Weekly-Build--$(date +'%Y-%m-%d')"
deploy:
  - provider: releases
    prerelease: true
    skip_cleanup: true
    token:
      secure: R/UG294tu6IY7TosmU34/4s2xzSdcUJduZJyQwUC+aGRIm+gSiUniO69MR4KOpStN5EO72RVmEJzFDMe0dpUN8DEoYfSl3ovTWmKF7OTOX/5cCuciR13CT2D8jUU72jws7BIuZbrjggzJWJ79G6zUGo8EyE6xnMoT4ODscT0Emw=
    file_glob: true
    file:
      - org.jcryptool.product/target/products/*.tar.gz
      - org.jcryptool.product/target/products/*.zip
    on:
      repo: jcryptool/core
      branch: develop
      condition: "$TRAVIS_EVENT_TYPE = cron"
  - provider: releases
    prerelease: false
    skip_cleanup: true
    token:
      secure: R/UG294tu6IY7TosmU34/4s2xzSdcUJduZJyQwUC+aGRIm+gSiUniO69MR4KOpStN5EO72RVmEJzFDMe0dpUN8DEoYfSl3ovTWmKF7OTOX/5cCuciR13CT2D8jUU72jws7BIuZbrjggzJWJ79G6zUGo8EyE6xnMoT4ODscT0Emw=
    file_glob: true
    file:
      - org.jcryptool.product/target/products/*.tar.gz
      - org.jcryptool.product/target/products/*.zip
    on:
      repo: jcryptool/core
      branch: master
      tags: true
