sudo: false
language: java
jdk:
- oraclejdk8
branches:
  only:
  - develop
before_install:
- git clone https://github.com/jcryptool/crypto.git ~/build/jcryptool/crypto
- echo "MAVEN_OPTS=-Xmx2048m" > ~/.mavenrc
install: true
script:
- mvn -f org.jcryptool.releng/pom.xml -DskipTests=true
before_deploy:
- git config --local user.name "Dominik Schadow"
- git config --local user.email "dominikschadow@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: R/UG294tu6IY7TosmU34/4s2xzSdcUJduZJyQwUC+aGRIm+gSiUniO69MR4KOpStN5EO72RVmEJzFDMe0dpUN8DEoYfSl3ovTWmKF7OTOX/5cCuciR13CT2D8jUU72jws7BIuZbrjggzJWJ79G6zUGo8EyE6xnMoT4ODscT0Emw=
  file:
    - jcryptool/core/org.jcryptool.product/target/products/jcryptool-1.0.0-linux.gtk.x86.tar.gz
    - jcryptool/core/org.jcryptool.product/target/products/jcryptool-1.0.0-linux.gtk.x86_64.tar.gz
    - jcryptool/core/org.jcryptool.product/target/products/jcryptool-1.0.0-macosx.cocoa.x86_64.tar.gz
    - jcryptool/core/org.jcryptool.product/target/products/jcryptool-1.0.0-win32.win32.x86.zip
    - jcryptool/core/org.jcryptool.product/target/products/jcryptool-1.0.0-win32.win32.x86_64.zip
  skip_cleanup: true
  on:
    repo: jcryptool/core
    branch: develop
