language: java
jdk:
  - oraclejdk8
before_install:
  - git clone https://github.com/jcryptool/crypto.git ~/build/jcryptool/crypto
install:
  - mvn -f org.jcryptool.releng/pom.xml -DskipTests=true -DMAVEN_OPTS=-"-Xmx1024m -XX:MaxPermSize=256m -XX:+UseGCOverheadLimit"