language: java
before_install:
  - git clone https://github.com/jcryptool/crypto.git jcryptool/crypto
install:
  - mvn -f org.jcryptool.releng/pom.xml -DskipTests=true -DMAVEN_OPTS=-"-Xmx512m -XX:MaxPermSize=128m"